fos_elastica:
    clients:
        default: { host: "%elastic_host%", port: "%elastic_port%" }
    indexes:
        user:
            index_name: user_%kernel.environment%
            types:
                user:
                    properties:
                        id:
                            type: integer
                        createdAt :
                            type : date
                        enabled : 
                            type : boolean
                        username : ~
                        firstname : ~
                        name : ~
                    persistence:
                        driver: orm
                        model: UserBundle\Entity\User
                        finder: ~
                        provider: ~
                        listener: ~