user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /
    host: "%domain%"
    
# Rest 
rest : 
  type : rest 
  resource : "routing_rest.yml"
  prefix : /api
  host: "%domain%"
