user_homepage:
    path:     /hello-world
    defaults: { _controller: UserBundle:Default:index }
    
# Implement all the routes of FOSUserBundle directly
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
# Other method: If you want to implement each part of FOSUserBundle separately   
#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile
#
#fos_user_register:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register
#
#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#    prefix: /resetting
#
#fos_user_change_password:
#    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#    prefix: /profile
