services:
#    user.example:
#        class: UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    user.web_service_tools:
        class: UserBundle\Utils\WebServiceTools
